import type { Metadata } from "next";
import "../styles/globals.css";
import Navbar from "../components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import "react-toastify/dist/ReactToastify.css";
config.autoAddCss = false;

// Fonts
import { Exo } from "next/font/google";
import Providers from "@/components/Providers/providers";
import { verifyToken } from "@/features/auth/server/auth.actions";
import { getLoggedUserCart } from "@/features/cart/server/cart.actions";
import { CartState } from "@/features/cart/store/cart.slice";
import { getUserOrders } from "@/features/orders/server/orders.actions";
import { OrdersState } from "@/features/orders/store/orders.slice";
import { getLoggedUserWishlist } from "@/features/wishlist/server/wishlist.action";
import { WishlistState } from "@/features/wishlist/store/wishlist.slice";

const exo = Exo({
  variable: "--font-exo",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "FreshCart",
  description: "Generated by create next app",
};

const defaultCartState: CartState = {
  cartId: null,
  numOfCartItems: 0,
  products: [],
  totalCartPrice: 0,
  isLoading: false,
  error: null,
};

const defaultOrdersState: OrdersState = {
  count: 0,
  data: [],
  isLoading: false,
  error: null,
};

const defaultWishlistState: WishlistState = {
  count: 0,
  data: [],
  isLoading: false,
  error: null,
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const authValues = await verifyToken();

  let cartState = defaultCartState;
  let ordersState = defaultOrdersState;
  let wishlistState = defaultWishlistState;

  if (authValues.isAuthenticated) {
    try {
      const cartResponse = await getLoggedUserCart();
      cartState = {
        cartId: cartResponse.data._id,
        numOfCartItems: cartResponse.numOfCartItems,
        products: cartResponse.data.products,
        totalCartPrice: cartResponse.data.totalCartPrice,
        isLoading: false,
        error: null,
      };
    } catch {
      cartState = defaultCartState;
    }

    try {
      const ordersData = await getUserOrders();
      ordersState = {
        count: ordersData.length,
        data: ordersData,
        isLoading: false,
        error: null,
      };
    } catch {
      ordersState = defaultOrdersState;
    }

    try {
      const wishlistResponse = await getLoggedUserWishlist();
      wishlistState = {
        count: wishlistResponse.count,
        data: wishlistResponse.data,
        isLoading: false,
        error: null,
      };
    } catch {
      wishlistState = defaultWishlistState;
    }
  }

  return (
    <html lang="en">
      <body
        className={`${exo.className} font-medium antialiased max-w-screen overflow-x-hidden`}
      >
        <Providers preloadedState={{ auth: authValues, cart: cartState, orders: ordersState, wishlist: wishlistState }}>
          <div className="max-w-screen overflow-x-hidden">
            <Navbar />
            {children}
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
